development:
  adapter: mysql2
  encoding: utf8
  database: db_dev
  pool: 5
  username: root
  password: dbroot
  socket: /var/run/mysqld/mysqld.sock
test:
  adapter: mysql2
  encoding: utf8
  database: db_dev
  pool: 5
  username: root
  password: dbroot
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: db_dev
  pool: 5
  username: root
  password: dbroot
  socket: /var/run/mysqld/mysqld.sock